---
title: "Comparing Common Genes with DML"
author: "Yaamini Venkataraman"
date: "2/12/2020"
output: github_document
---

In this R Markdown document, I'll examine GOSlim terms in genes with DML common between *C. gigas* and *C. virginica*.

# Set up R Markdown file

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install packages

```{r}
#install.packages("dichromat")
require("dichromat")
```

# Obtain session information

```{r}
sessionInfo() #Obtain session information
```

# Import and reformat data

```{r}
commonBPGOSlim <- read.delim("commonBlastquery-GOslim-BP.sorted.unique.noOther", sep = "\t", header = FALSE) #Import unique BP GOslim terms without any "other biological processes" entries. File is tab-delimited and does not have a header.
colnames(commonBPGOSlim) <- c("geneID", "GOSlim") #Rename columns
head(commonBPGOSlim) #Confirm import
```

```{r}
commonBPGOSlimCounts <- as.data.frame(table(commonBPGOSlim$GOSlim)) #Count the frequency of each GOslim term
colnames(commonBPGOSlimCounts) <- c("GOSlim", "frequency") #Rename columns
head(commonBPGOSlimCounts) #Confirm counting
```

```{r}
#Signal transduction, death, cell adhesion, and cell-cell signaling are not represented in this dataset.
notCommonBPGOSlimCounts <- data.frame("GOSlim" = c("signal transduction", "death", "cell adhesion", "cell-cell signaling"),
                                      "frequency" = c(0,0,0,0)) #Create dataframe with GOSlim terms not represented by the overlap data
head(notCommonBPGOSlimCounts) #Confirm dataframe creation
```

```{r}
fullBPGOSlimCounts <- rbind(commonBPGOSlimCounts, notCommonBPGOSlimCounts) #Add missing information to dataset
tail(fullBPGOSlimCounts) #Confirm addition
```

```{r}
fullBPGOSlimCounts$percentage <- (fullBPGOSlimCounts$frequency/sum(fullBPGOSlimCounts$frequency)*100) #Create a new column with percentages of GOSlim terms instead of raw counts
tail(fullBPGOSlimCounts) #Confirm column creation
```

```{r}
fullBPGOSlimCounts <- fullBPGOSlimCounts[c(13, 12, 11, 10, 9,
                                           1, 3, 2,
                                           8,
                                           5, 6, 7, 3),] #Reorganize rows based on broader functions. Rows are development, stress response, and metabolic processes.
head(fullBPGOSlimCounts) #Confirm organization
```

```{r}
fullBPGOSlimCounts$GOSlim <- c("Cell-Cell Signaling", "Cell Adhesion", "Death", "Signal Transduction", "Transport",
                                 "Cell Cycle and Proliferation", "Developmental Processes", "Cell Organization and Biogenesis",
                                 "Stress Response",
                                 "DNA Metabolism", "RNA Metabolism", "Protein Metabolism", "Other Metabolic Processes") #Capitalize labels
head(fullBPGOSlimCounts) #Confirm capitalization
```

# Barplot

```{r}
#pdf("2020-02-12-Common-BP-GOSlim-DML-Gene-Overlaps.pdf", width = 11, height = 8.5) #Save as a pdf

par(mar = c(5, 20, 1, 1)) #Change figure boundaries

commonBarsGOSlim <- barplot(fullBPGOSlimCounts$percentage,
                            horiz = TRUE,
                            axes = FALSE, 
                            xlim = c(0,22),
                            col = c(rep(plotColors2[2], times = 5),
                                    rep(plotColors2[4], times = 3),
                                    rep(plotColors2[5], times = 1),
                                    rep(plotColors2[1], times = 4))) #Create a barplot that is horizontal (horiz = TRUE). Use axes = FALSE to remove all axes. Set xlim based on maximum percentage value. Colors correspond to broader GOSlim groupings. Save plot as a new object.

axis(side = 2, at = commonBarsGOSlim, labels = fullBPGOSlimCounts$GOSlim, tick = FALSE, las = 2, col = "grey80", cex.axis = 1.5) #Add y-axis with GOSlim terms from BPGOSlimCounts. Place labels at specific barplot values from barsGOSlim. Remove tick marks (tick) and change orientation of labels (las)

axis(side = 1, at = seq(from = 0, to = 22, by = 2), cex = 1.2, col = "grey80") #Add x-axis
mtext(side = 1, "Common Genes with DML (%)", line = 3, cex = 1.5) #Add x-axis label

#par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE) #Create new plot
#plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n") #Add new plot on top of current plot
#legend("bottomleft",
#       xpd = TRUE,
#       legend = c("General Activity", "Development", "Stress Response", "Metabolic Processes"),
#       pch = 22, 
#        col = "black", 
#        pt.bg = c(plotColors[2], plotColors[4], plotColors[5], plotColors[1]),
#       bty = "n") #Place a legend in the bottom left of the figure with no box

#dev.off()
```



